### ISSUE TITLE
SDK does not properly handle empty response bodies on successful requests

### ISSUE THREAD

**Issue by tiwillia** [openshift-online/ocm-sdk-go#212]
The following error is produced when making a successful request to the accountsmgmt Notify() endpoint:
```
 OCM-CA-9: ReadObject: expect { or , or } or n, but found , error found in #0 byte of ...||..., bigger context ...||...
```

**Comment by tiwillia** [comment]
@vkareh Eric Himmelreich mentioned that you had looked into this at some point and determined it to be some issue in the metamodel. Could you elaborate a bit here?

**Comment by igoihman** [comment]
This is fixed in the recent metamodel release
