### ISSUE TITLE
Support override of authentication's error handler

### ISSUE THREAD

**Issue by JameelB** [openshift-online/ocm-sdk-go#319]
Currently, the authentication package has an internal [error handler](https://github.com/openshift-online/ocm-sdk-go/blob/v0.1.152/authentication/handler.go#L779) which cannot be overridden. 

It would be great if we can add support to override this so that we can handle our errors consistently throughout our application which uses this package. Would this be possible?

**Comment by jhernand** [comment]
@JameelB Can you provide an example of the kind of customized error handling that you would like to do?

**Comment by jhernand** [comment]
@JameelB I see. Can you share an example of the JSON response body that you want to send?

**Comment by JameelB** [comment]
@jhernand Here's an example JSON response:

```
{
   "id":"11",
   "kind":"Error",
   "href":"/api/managed-services-api/v1/errors/11",
   "code":"MGD-SERV-API-11",
   "reason":"Bearer token is expired",
   "operation_id":"1nKwdh6ZQOyxSdlsJxOphbGs7Nq"
}
```

**Comment by jhernand** [comment]
Thanks @JameelB. So you need to change the error identifier and the error code, and you need to add an operation identifier for each request. We could provide a generic mechanism to override completely the error reporting, but then it would be an open door to return any kind of thing, including valid responses, and I would prefer to avoid that. Would it be enough for you if we add to the builder of the handler methods to set the error identifier and code, and a method to set a function that returns the operation identifier for the request? Would be something like this:

```go
// Define your own function to extract the operation identifier from
// the request:
func myOperatiIDExtractor(r *http.Request) string {
        return ...
}

// Create the handler using custom error identifer, service identifier
// and operation id extractor:
handler, err := authentication.NewHandler().
        Logger(logger).
        KeysURL(...).
        Service("MGD-SERV-API").
        Error("11").
        OperationID(myOperationIDExtractor).
        Build()
```

Would that satisfy your requirement?

**Comment by JameelB** [comment]
That's perfect for us @jhernand, thank you!
